<font size="1">  
<h1>Subject: Home Work  5<h1>
    <p>Shahrood University of Technology (SUT)<p>
    <p> Artificial Intelligence</p>
    <p> Student Number: 40103834 </p>
    <p style="color:yellow;">Author: Ehsan Paydar</p> 
    </font>  

<h1 style="color:#a21441;">Import Library</h1>

In [1]:
import gym
import numpy as np

<h1 style="color:#00a693;">Define variables</h1>


In [3]:
env = gym.make('FrozenLake-v1', map_name="8x8", is_slippery=True)
num_states = env.observation_space.n
num_actions = env.action_space.n
q_table = np.zeros((num_states, num_actions))

<h1 style="color:#a21441;">Determination of parameters</h1>

In [4]:
num_episodes = 10000
max_steps_per_episode = 100
learning_rate = 0.1
discount_rate = 0.99
exploration_rate = 0.05
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

<h1 style="color:#00a693;">Q-Learning Algorithm</h1>


In [5]:
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        # Exploration-exploitation trade-off
        exploration_rate_threshold = np.random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        # Take new action
        new_state, reward, done, info = env.step(action)

        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
                                 learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
                       (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    # Print rewards for each episode
    print("Reward for episode {}: {}".format(episode, rewards_current_episode))

Reward for episode 0: 0.0
Reward for episode 1: 0.0
Reward for episode 2: 0.0
Reward for episode 3: 0.0
Reward for episode 4: 0.0
Reward for episode 5: 0.0
Reward for episode 6: 0.0
Reward for episode 7: 0.0
Reward for episode 8: 0.0
Reward for episode 9: 0.0
Reward for episode 10: 0.0
Reward for episode 11: 0.0
Reward for episode 12: 0.0
Reward for episode 13: 0.0
Reward for episode 14: 0.0
Reward for episode 15: 0.0
Reward for episode 16: 0.0
Reward for episode 17: 0.0
Reward for episode 18: 0.0
Reward for episode 19: 0.0
Reward for episode 20: 0.0
Reward for episode 21: 0.0
Reward for episode 22: 0.0
Reward for episode 23: 0.0
Reward for episode 24: 0.0
Reward for episode 25: 0.0
Reward for episode 26: 0.0
Reward for episode 27: 0.0
Reward for episode 28: 0.0
Reward for episode 29: 0.0
Reward for episode 30: 0.0
Reward for episode 31: 0.0
Reward for episode 32: 0.0
Reward for episode 33: 0.0
Reward for episode 34: 0.0
Reward for episode 35: 0.0
Reward for episode 36: 0.0
Reward for 

<h1 style="color:#a21441;">Print updated Q-table</h1>

In [6]:
print("\n\nQ-table:")
print(q_table)



Q-table:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
